---
title: Profematesvalencia.net
author: Ezequiel
email: marcel.soulodre@gmail.com
description: Una de mis principales cualidades es la importancia que le doy al proceso
  de aprendizaje. Todos aprendemos a ritmos distintos y es labor del docente identificar
  cuales son los métodos que generan mejores resultados, siendo lo mas importante
  el volver atrás para solucionar o reforzar algunos conceptos clave.
baseurl: ''
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
